version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: myphp8
    volumes:
      - ./web:/var/www
    working_dir: /var/www
